= Introduction <sec:intro>

The AI ecosystem's attack surface is large and growing. @girnus2026faultlines catalogs 6,086 unique AI-related CVEs from 2018 to 2025, spanning hardware through the agentic application layer, with a 34.6% year-over-year increase; nearly half of scored AI vulnerabilities are high- or critical-severity. The CISA Known Exploited Vulnerabilities catalog (KEVs) reached 1,484 entries by end of 2025 @cisa2025kev, and AI infrastructure is beginning to appear: inference servers like Nvidia `Triton` and `vLLM` have disclosed RCE-class bugs, though most have not yet been confirmed exploited in the wild. The ML training and inference stack (from chip RTL through orchestration layers to the chatbot TUI) is a conventional software system, and it has conventional software vulnerabilities. Formal methods can help.

== AI Security <sec:ai-security>

"AI security" means different things to different communities. Dangerous capability evaluations ask whether a model can synthesize bioweapons or write zero-day exploits -- the model itself is the threat. That is not what we mean here. By AI security we mean the confidentiality, integrity, and availability of the _systems that train and serve AI models_. The most important invariant is model weight confidentiality: if an attacker exfiltrates a frontier model's weights, every downstream safety measure (RLHF, system prompts, deployment controls) can be stripped away at the attacker's leisure (including when the attacker is the same AI that got exfiltrated). But weight confidentiality is not the only invariant. Training data poisoning violates integrity. Container escapes by agentic systems violate isolation. Supply chain compromises in ML frameworks violate the assumption that the code you ran is the code you audited. In what follows, we map where formal methods has traction.

#footnote[One common thread is _confinement_: restricting what information crosses a boundary, and in which direction. Lampson's 1973 note @lampson1973confinement states confinement rules for reasoning about when a program can or cannot leak information through legitimate or covert channels. @yampolskiy2012leakproofing extends this framing to AI, defining the AI Confinement Problem as restricting an AI to an environment from which it cannot exchange unauthorized information with the outside world @lesswrong2020aiboxing. Classical AI safety was skeptical of boxing -- Yudkowsky's AI Box experiments were meant to show it couldn't work. Recent work from AI Control @greenblatt2024aicontrol and Safeguarded AI @dalrymple2024safeguardedai has reignited interest.

@dalrymple2024guaranteedsafeai propose a framework for "guaranteed safe AI" built on world models, safety specifications, and verifiers. @tegmark2023provablysafe argue that provably safe systems are the only path to controllable AGI. @dalrymple2024safeguardedai operationalizes a version of this via a gatekeeper architecture where every action requires a machine-checkable proof. These are important papers, and they are ambitious by design. The present document is their complement. We are not trying to solve the alignment problem with formal methods. We are trying to harden the infrastructure that AI systems run on -- the same kind of work that has already been done for compilers, operating systems, and network protocols.

The connection between the two projects is direct: a proof-carrying code @necula1997pcc architecture is only as strong as the execution environment that enforces it. @dougherty2025formalconfinement prototypes the interface layer -- specifications in `Lean` that the AI must prove its output satisfies. The tractable problems in this paper operate below that interface, on the verified runtimes, hardened sandboxes, and correct compilers that any confinement protocol has to sit on top of.]

== Secure Program Synthesis <sec:sps>

@vonhippel2026sfo frames this infrastructure work as the Scalable Formal Oversight (SFO) research program: "about the box, not the monster you put in it." SFO is the observation that formal verification of AI infrastructure is independent of the model -- you do not need to solve alignment to harden a container runtime or verify a compiler pass. The tractable problems below are SFO problems.

AI is also accelerating formal methods itself, which makes SFO problems more tractable than they were five years ago. @dodds2025specsdontexist argues that as AI lowers the cost of proof, the bottleneck shifts to _specification_ -- the hard part is saying what you mean, not proving that you said it correctly. This observation bears on the tractable problems below in both directions: the projects get easier as secure program synthesis matures, and several of them are themselves contributions to that maturation.
