// Tag: audit-log-integrity
// Layers: execution-harness, orchestration-cloud
// Category: widget

== Audit Log Integrity and Session State Channels <sec:audit-log-integrity>

The audit log is the primary accountability mechanism for deployed AI systems. Regulators, red teams, and incident responders all depend on the same thing: a complete, tamper-evident record of what the model did. If log entries can be suppressed, falsified, or selectively deleted, the system is effectively unauditable --- and any safety claim that rests on "we can review the logs" collapses. Append-only storage and cryptographic log chaining (in the style of Certificate Transparency @laurie2014ct) provide tamper _evidence_, but the implementations are not formally verified. The gap between "we use Merkle trees" and "no API call sequence available to the serving infrastructure can modify a committed entry" is exactly the gap formal methods fills.

There is a subtler problem on the same boundary. When a model's output or summary is written back to session state for future context windows, a persistent side channel is created. A misaligned model can encode messages in session state that survive request boundaries --- instructions to future invocations of itself, breadcrumbs for capability accumulation, or data staged for later exfiltration. This channel is invisible to the output filter, which inspects the response returned to the user, not the write-back to the session store. The threat model is not hypothetical: any system that persists conversation summaries, scratchpads, or tool-call results across requests has this surface.

The two problems are linked by a common structure: both involve a write path that must satisfy integrity constraints, and both fail silently when the constraints are violated. A corrupted log and a poisoned session store both look normal from outside the system until someone audits the contents --- and the audit itself depends on the log being intact.

=== Solution/project Sketch <sec:audit-log-integrity-sketch>

For log integrity, build an Alloy model of the storage API and permission system. The specification: no sequence of API calls available to any principal in the serving infrastructure (model, harness, orchestrator) can modify or delete a committed log entry. This is a finite-state check over the permission graph and the storage state machine; Alloy's bounded model checking handles it directly. Separately, specify logging _completeness_ as a TLA+ liveness property on the serving state machine: every request that reaches forward-pass execution produces exactly one log entry, and that entry is committed before the response is returned to the caller. The completeness property catches suppression; the Alloy model catches tampering.

For session state, apply information flow analysis. Model the session store as shared memory and the write-back function as the interface under test. The noninterference property: the content written to session state must be a function only of authorized inputs (the model's declared output schema, the user's message, the tool results). Any information flow from the model's hidden state to the session store that is not mediated by the declared output path is a violation. This is verifiable as a pre/postcondition contract on the write-back function --- specify the allowed content, prove the function produces only that content. Dafny is a natural fit: the write-back function is small, the specification is a refinement type on the output, and the verifier handles the quantifier reasoning automatically.
