// Tag: capability-accumulation
// Layers: execution-harness
// Category: widget

== Capability Accumulation and Loop Termination <sec:capability-accumulation>

A single tool call in an agentic harness is usually benign. Read a file, run a shell command, make an HTTP request --- each is authorized individually by whatever permission system the harness enforces. The problem is composition: read file + shell exec + HTTP request = exfiltrate a secret key. No single call crossed a policy boundary, but the _sequence_ did. This is the weird machines problem @bratus2011weird applied to AI tool use. In a weird machine exploit, individually legitimate instruction sequences compose into unintended computation; here, individually permitted tool calls compose into unauthorized capability. Capability-based security (Capsicum @watson2010capsicum, seL4 capabilities) provides the right theoretical framing --- authority should be confined, attenuated, and non-ambient --- but no formal model for AI harness tool sets exists. Current harnesses enforce per-call checks and hope for the best.

The second half of the problem is resource control. Agentic loops can run indefinitely: the model calls a tool, observes the result, decides to call another tool, and repeats. Resource budgets (step count, token count, wall time) are the standard defense, but the enforcement is ad hoc. If the termination check runs _after_ tool dispatch rather than _before_, an off-by-one in the budget counter lets the agent squeeze in one extra call --- which may be the exfiltration call. If the budget is checked in application code that the agent can influence (e.g., by manipulating session state), the bound is not a bound.

These two problems reinforce each other. An agent trying to accumulate capabilities needs enough steps to build the chain; a tight, formally verified resource budget limits how long a chain can get. Conversely, an agent trying to exhaust a resource budget benefits from capability accumulation --- it can use early steps to expand its own authority and spend later steps exploiting it.

=== Solution/project Sketch <sec:capability-accumulation-sketch>

Model the tool set as a process algebra (CSP or CCS), with each tool assigned typed I/O channels and a declared side-effect footprint. The harness dispatch loop becomes a process that composes tool invocations sequentially, threading session state as a shared channel. Dangerous states --- exfiltration (data crosses session boundary), persistence (state survives session teardown), privilege escalation (capability set grows) --- are specified as reachability predicates. Standard model checking (FDR for CSP, or SPIN on an equivalent Promela encoding) then answers the question: does any interleaving of tools from the permitted set reach a dangerous state? The tool set is finite and the state space is bounded by session lifetime, so this is tractable.

For information flow, apply noninterference analysis to the dispatch code itself. The property: no sequence of tool calls with session-bounded inputs can produce output observable outside the session boundary. This is a standard IFC problem; Jif-style @myers1999jflowpractical label checking on the dispatch layer would suffice. The labels track which data came from which tool call, and the type system rejects any dispatch sequence that routes high-confidentiality data to a low-integrity output channel.

For loop termination, verify the resource budget as an LTL liveness property on the harness state machine: _every execution eventually reaches a terminal state_. The budget counter must be monotonically non-decreasing, and the termination check must execute _before_ each tool dispatch, not after. This rules out the off-by-one class. The invariant --- counter increments before dispatch, dispatch is gated on counter less than bound --- is straightforward to verify with Frama-C (for a C harness) or Dafny (for a managed-language harness). The contract is small: a precondition on the dispatch function and a loop invariant on the main agent loop.
