// Tag: edge-policy-verification
// Layers: execution-harness, orchestration-cloud
// Category: widget
// Authors: quinn, maxvh

#import "../common/fns.typ": related-layers

== Edge Policy Verification <sec:edge-policy>

#related-layers("edge-policy-verification")

The API gateway in front of an inference service handles authentication, rate limiting, and authorization before a request ever reaches the model. Each of these is a distinct protocol with distinct failure modes, and they interact. JWT algorithm confusion @cve2015jwtalg let attackers forge tokens by switching from RSA to HMAC verification --- a bug that lived in production libraries for years because the state space of the auth handshake was never systematically explored. OAuth 2.0 flows compound the problem: the redirect-based token exchange has enough moving parts (authorization codes, refresh tokens, PKCE challenges, session binding) that implementation errors routinely produce exploitable states. These are not novel observations, but the standard response --- unit tests and penetration testing --- samples the state space rather than covering it.

Rate limiting in distributed deployments is a second, largely independent class of bug. The typical architecture uses distributed counters (`Redis`, or an in-process sliding window with gossip) to enforce per-key quotas. Under concurrent writes, race conditions allow burst traffic to exceed policy. The failure is often silent: the system reports correct enforcement while the actual request count drifts above the limit. Temporal logic can express the property you actually want --- "over any window of length $T$, the count for key $k$ does not exceed $N$" --- and model checking can verify that a given counter protocol satisfies it under all interleavings, not just the ones your load test happened to hit.

The third piece is authorization for agent-originated requests. In agentic deployments, the model generates tool calls --- HTTP requests, database queries, shell commands --- that carry the _human_ session's credentials. The model acts on behalf of the user but is not the user; it is a textbook confused deputy. If the routing logic does not attenuate authority, a prompt injection or jailbreak that causes the model to emit an unexpected tool call inherits whatever permissions the session holds. The question is whether the set of actions reachable through model-generated requests is a strict subset of the actions the human intended to authorize, and this is a containment property amenable to formal analysis.

These three concerns --- authentication correctness, quota enforcement, and agent authority attenuation --- share a common trait: each is a small protocol with a large state space, running at a trust boundary. They are individually tractable for current FM tools but rarely analyzed together, even though a bug in one can undermine the guarantees of the others.

=== Solution/project Sketch <sec:edge-policy-sketch>

The project decomposes into three workstreams that share a common formal model of the gateway's request lifecycle. First, model the authentication state machine (`JWT` issuance, validation, algorithm selection, key lookup) in `TLA+` and verify that no reachable state admits a token accepted under an unintended algorithm or expired credential. Extend this with a `ProVerif` or `Tamarin` (TODO: cite tool papers) model of the full OAuth 2.0 flow as instantiated by the gateway, producing machine-checked proofs of token secrecy and session binding. Second, express the rate-limit policy as a temporal logic formula and verify the distributed counter implementation against it in `TLA+`, covering all process interleavings and crash-recovery scenarios. Where the counter uses shared mutable state, apply `Iris` or another concurrent separation logic to prove the monotonicity invariant (the counter never decreases except at window expiry) under concurrent writes. Third, model agent authority as a capability system in `Alloy`: the human session holds a capability set, the model's tool-call interface holds an attenuated subset, and the routing logic mediates between them. Verify that no sequence of model-generated requests can reach a capability outside the attenuated set --- a direct confused-deputy analysis of the gateway's forwarding rules. The final deliverable is a verified reference gateway configuration (or shim) with proofs covering all three properties, plus a test harness that regression-checks deployed gateways against the formal spec.
