== Hardware and Physical Supply Chain <sec:hardware-supply-chain>

At the bottom of the stack is the silicon itself: the GPU, TPU, and NPU dies that run every training and inference workload, and the global supply chain that produces them. Compromise here is uniquely durable --- a hardware trojan survives every software update, every OS reinstall, every firmware reflash. It is also uniquely opaque: you cannot read out the RTL of a fabricated chip to check what it does.

=== Chip Architecture <sec:chip-architecture>

The RTL design of a modern AI accelerator is entirely proprietary. NVIDIA does not publish the register-transfer-level description of its GPU compute cores; neither do Google (TPUs), AMD, or any other vendor. This means the formal methods community cannot verify what the silicon actually computes. We take it on trust that an H100's tensor cores implement matrix multiplication correctly, that its memory controllers enforce isolation between MIG partitions, and that no undocumented debug interfaces exist. Classen et al. @classen2024evilfromwithin demonstrated that a hardware trojan implanted in a Xilinx Vitis AI DPU could backdoor a traffic-sign recognition model by replacing just 30 of 43,000 parameters at the accelerator level --- expanding the circuit by 0.24% with zero runtime overhead, invisible to all software-side defenses. The attack needed no cooperation from the model or the training pipeline; the accelerator alone was sufficient.

This opacity is not uniformly distributed. FPGAs are the exception: their designs are written in RTL that the deployer controls, synthesized through a known toolchain, and reprogrammable in the field. An FPGA-based network tap, for example, can have its entire datapath formally verified from specification to bitstream --- a property no ASIC-based accelerator can match. This is why @sec:network-tap-fpga proposes FPGA taps as a verification target: they are the one place in the hardware stack where we _own_ the design and can prove something about it. On the GPU side, the architecture determines what isolation primitives are available to driver software. Whether a verified driver (@sec:sel4-gpu) can enforce strong tenant isolation depends on what the hardware exposes --- and right now, we are relying on vendor documentation rather than verified specs for that interface.

=== Physical Security <sec:physical-security>

Confidential computing has reached the GPU. NVIDIA's H100 supports a hardware-rooted TEE that, in conjunction with CPU-side enclaves (Intel TDX, AMD SEV-SNP), can encrypt model weights in transit and at rest on the device, with attestation that the firmware and driver stack have not been tampered with. This matters for AI because model weights are the single most valuable artifact in the ecosystem --- worth billions in training compute --- and multi-tenant cloud deployments expose them to the cloud operator's entire software stack. Side-channel attacks add another dimension: GPU power analysis and electromagnetic emanation have been demonstrated against cryptographic implementations on GPUs, and model-extraction attacks via cache timing and memory access patterns are an active area of research.

For training clusters of 10,000+ GPUs, the physical supply chain itself becomes a target. Every node in the cluster must be attested before it receives model weights or gradient updates. Every network link between nodes carries data that, if intercepted or modified, could poison a training run or exfiltrate a model. FPGA-based network taps (@sec:network-tap-fpga) address the link-level problem: a tap with a formally verified packet-processing pipeline can guarantee that it faithfully mirrors traffic without injection or modification --- a property that no software tap running on a general-purpose OS can credibly claim.
